### ISSUE TITLE
Make this available on melpa?

### ISSUE THREAD

**Issue by bdwalton** [CyberShadow/term-title#1]
Wondering if you'd be willing to get this published on melpa so it's easily available through standard tooling in emacs?

**Comment by CyberShadow** [comment]
I disagree with MELPA's philosophy of rejecting packages because of disagreements about code style, so I will not be submitting it to MELPA myself.

**Comment by bdwalton** [comment]
The first item in this section?
https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion

**Comment by CyberShadow** [comment]
Essentially, and their position that disagreements about something inherently incredibly subjective that reasonable people may disagree on warrants rejection. They've done so several times in the past, even in cases where common sense might suggest that following the rules as written would worsen the situation. As such, I'm not particularly sympathetic to their project.

I would recommend using a modern package manager such as [straight.el](https://github.com/radian-software/straight.el) (plus [use-package](https://github.com/jwiegley/use-package)) over package.el for other reasons as well.

If you'd really like to use package.el, you could use [my personal ELPA](https://elpa.thecybershadow.net/).

**Comment by bdwalton** [comment]
Ok, I'll give straight a try. I'm only just modernizing a very ancient
config so don't mind making that switch now. Thanks for the nudge.
